/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lms;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author abinash
 */
public class StudentDashboard extends javax.swing.JFrame {
 
    /**
     * Creates new form StudentDashboard
     */
    public StudentDashboard() {
        initComponents();
        cardLayout = (CardLayout)(container.getLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sideBar = new javax.swing.JPanel();
        courseBar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        feesBar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        todoBar = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cardBar = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        container = new javax.swing.JPanel();
        courseContainer = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        feesContainer = new javax.swing.JPanel();
        todoContainer = new javax.swing.JPanel();
        cardContainer = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        sideBar.setBackground(new java.awt.Color(60, 73, 88));

        courseBar.setBackground(new java.awt.Color(69, 90, 125));
        courseBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                courseBarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                courseBarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                courseBarMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Courses");

        javax.swing.GroupLayout courseBarLayout = new javax.swing.GroupLayout(courseBar);
        courseBar.setLayout(courseBarLayout);
        courseBarLayout.setHorizontalGroup(
            courseBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, courseBarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        courseBarLayout.setVerticalGroup(
            courseBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        feesBar.setBackground(new java.awt.Color(69, 87, 113));
        feesBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                feesBarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                feesBarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                feesBarMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fees");

        javax.swing.GroupLayout feesBarLayout = new javax.swing.GroupLayout(feesBar);
        feesBar.setLayout(feesBarLayout);
        feesBarLayout.setHorizontalGroup(
            feesBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, feesBarLayout.createSequentialGroup()
                .addGap(0, 43, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        feesBarLayout.setVerticalGroup(
            feesBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        todoBar.setBackground(new java.awt.Color(69, 87, 113));
        todoBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                todoBarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                todoBarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                todoBarMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Todo");

        javax.swing.GroupLayout todoBarLayout = new javax.swing.GroupLayout(todoBar);
        todoBar.setLayout(todoBarLayout);
        todoBarLayout.setHorizontalGroup(
            todoBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, todoBarLayout.createSequentialGroup()
                .addGap(0, 43, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        todoBarLayout.setVerticalGroup(
            todoBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        cardBar.setBackground(new java.awt.Color(69, 87, 113));
        cardBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardBarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cardBarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cardBarMouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Card");

        javax.swing.GroupLayout cardBarLayout = new javax.swing.GroupLayout(cardBar);
        cardBar.setLayout(cardBarLayout);
        cardBarLayout.setHorizontalGroup(
            cardBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardBarLayout.createSequentialGroup()
                .addGap(0, 43, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        cardBarLayout.setVerticalGroup(
            cardBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
        sideBar.setLayout(sideBarLayout);
        sideBarLayout.setHorizontalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(courseBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(feesBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(todoBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cardBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sideBarLayout.setVerticalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(courseBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(feesBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(todoBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(cardBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        container.setBackground(new java.awt.Color(255, 255, 255));
        container.setLayout(new java.awt.CardLayout());

        courseContainer.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(245, 245, 245));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Course Id:");

        jTextField3.setBackground(new java.awt.Color(240, 240, 240));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField3.setText("Username");
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField3.setDragEnabled(true);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton1.setText("search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel4.setBackground(new java.awt.Color(230, 230, 230));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 797, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout courseContainerLayout = new javax.swing.GroupLayout(courseContainer);
        courseContainer.setLayout(courseContainerLayout);
        courseContainerLayout.setHorizontalGroup(
            courseContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        courseContainerLayout.setVerticalGroup(
            courseContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(courseContainerLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        container.add(courseContainer, "courseContainer");

        feesContainer.setBackground(new java.awt.Color(0, 51, 255));

        javax.swing.GroupLayout feesContainerLayout = new javax.swing.GroupLayout(feesContainer);
        feesContainer.setLayout(feesContainerLayout);
        feesContainerLayout.setHorizontalGroup(
            feesContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 797, Short.MAX_VALUE)
        );
        feesContainerLayout.setVerticalGroup(
            feesContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 619, Short.MAX_VALUE)
        );

        container.add(feesContainer, "feesContainer");

        todoContainer.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout todoContainerLayout = new javax.swing.GroupLayout(todoContainer);
        todoContainer.setLayout(todoContainerLayout);
        todoContainerLayout.setHorizontalGroup(
            todoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 797, Short.MAX_VALUE)
        );
        todoContainerLayout.setVerticalGroup(
            todoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 619, Short.MAX_VALUE)
        );

        container.add(todoContainer, "todoContainer");

        cardContainer.setBackground(new java.awt.Color(51, 255, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout cardContainerLayout = new javax.swing.GroupLayout(cardContainer);
        cardContainer.setLayout(cardContainerLayout);
        cardContainerLayout.setHorizontalGroup(
            cardContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardContainerLayout.createSequentialGroup()
                .addContainerGap(380, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(317, 317, 317))
        );
        cardContainerLayout.setVerticalGroup(
            cardContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardContainerLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(471, Short.MAX_VALUE))
        );

        container.add(cardContainer, "cardContainer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(sideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sideBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // handel overing effect
    // <editor-fold defaultstate="collapsed" desc="handel overing effect">     
    private void courseBarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courseBarMouseEntered
        if(activeSideBar.equalsIgnoreCase("courseBar")){
            return;
        }
        setColor(courseBar);
        
    }//GEN-LAST:event_courseBarMouseEntered

    private void courseBarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courseBarMouseExited
        if(activeSideBar.equalsIgnoreCase("courseBar")){
            return;
        } 
        resetColor(courseBar);
    }//GEN-LAST:event_courseBarMouseExited

    private void feesBarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feesBarMouseEntered
        if(activeSideBar.equalsIgnoreCase("feesBar")){
            return;
        } 
        setColor(feesBar);
    }//GEN-LAST:event_feesBarMouseEntered

    private void feesBarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feesBarMouseExited
        if(activeSideBar.equalsIgnoreCase("feesBar")){
            return;
        } 
        resetColor(feesBar);
    }//GEN-LAST:event_feesBarMouseExited

    private void todoBarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_todoBarMouseEntered
        if(activeSideBar.equalsIgnoreCase("todoBar")){
            return;
        } 
         setColor(todoBar);
    }//GEN-LAST:event_todoBarMouseEntered

    private void todoBarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_todoBarMouseExited
         if(activeSideBar.equalsIgnoreCase("todoBar")){
            return;
        } 
         resetColor(todoBar);
    }//GEN-LAST:event_todoBarMouseExited

    private void cardBarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardBarMouseEntered
         if(activeSideBar.equalsIgnoreCase("cardBar")){
            return;
        } 
         setColor(cardBar);
    }//GEN-LAST:event_cardBarMouseEntered

    private void cardBarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardBarMouseExited
        if(activeSideBar.equalsIgnoreCase("cardBar")){
            return;
        } 
        resetColor(cardBar);
    }//GEN-LAST:event_cardBarMouseExited

    
    
    // handel nav click event
    private void courseBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courseBarMouseClicked
        if(activeSideBar.equalsIgnoreCase("courseBar")){
            return;
        } 
        
      setActiveBar(activeSideBar,"courseBar");
      cardLayout.show(container, "courseContainer");
    }//GEN-LAST:event_courseBarMouseClicked

    private void feesBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feesBarMouseClicked
       if(activeSideBar.equalsIgnoreCase("feesBar")){
            return;
        } 
      
      setActiveBar(activeSideBar,"feesBar");
      cardLayout.show(container, "feesContainer");
    }//GEN-LAST:event_feesBarMouseClicked

    private void todoBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_todoBarMouseClicked
       if(activeSideBar.equalsIgnoreCase("todoBar")){
            return;
        } 
       
      setActiveBar(activeSideBar,"todoBar");
      cardLayout.show(container, "todoContainer");
    }//GEN-LAST:event_todoBarMouseClicked

    private void cardBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardBarMouseClicked
       if(activeSideBar.equalsIgnoreCase("cardBar")){
            return;
        } 
      
      setActiveBar(activeSideBar,"cardBar");
      cardLayout.show(container, "cardContainer");
    }//GEN-LAST:event_cardBarMouseClicked

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    private JPanel getPanel(String panelName){
        if(panelName.equalsIgnoreCase("courseBar")){
            return courseBar;
        } 
        else if(panelName.equalsIgnoreCase("feesBar")){
            return feesBar;
        } 
        else if(panelName.equalsIgnoreCase("todoBar")){
            return todoBar;
        } 
        else if(panelName.equalsIgnoreCase("cardBar")){
            return cardBar;
        } 
        
        return new JPanel();
    }
    
    private void setActiveBar(String pre, String next){
        activeSideBar=next;
        resetColor(getPanel(pre));
        setColor(getPanel(next));
    }
    
    private void setColor(javax.swing.JPanel givenPanel){
        givenPanel.setBackground(new Color(69,90,125));  
    }
    
    private void resetColor(javax.swing.JPanel givenPanel){
        givenPanel.setBackground(new Color(69,87,113));  
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDashboard().setVisible(true);
            } 
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardBar;
    private javax.swing.JPanel cardContainer;
    private javax.swing.JPanel container;
    private javax.swing.JPanel courseBar;
    private javax.swing.JPanel courseContainer;
    private javax.swing.JPanel feesBar;
    private javax.swing.JPanel feesContainer;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel sideBar;
    private javax.swing.JPanel todoBar;
    private javax.swing.JPanel todoContainer;
    // End of variables declaration//GEN-END:variables
    private String activeSideBar="courseBar";
    private CardLayout cardLayout;
}
